all: compile run

compile:
	g++ -std=c++17 ./gameTest.cpp ../game.cpp ../../Items/item.cpp ../../Items/nontools.cpp ../../Items/tools.cpp ../../Menu/Menu.cpp ../../Exception/Exception.hpp

run:
	./a.out